---
title: "The ABCs of Data"
---

## ABCs of Data Resources

- [Fillable ABCs of Data Worksheet](https://docs.google.com/document/d/1giyIqZkXTtKAat7HYg4WTHORJRgEsnHDP9k-3Oqq-rY/edit?tab=t.0#heading=h.aqhwpw4oerj1) - Interactive Google Doc version
- [ABCs of Data Printable (PDF)](downloads/abcs-of-data.pdf) - Download the English version
- [ABCs of Data - Spanish (PDF)](downloads/abcs-of-data-spanish.pdf) - Download the Spanish version
- [Embracing Uncertainty in Science: The ABCs of Data and the Confidence Updater (PDF)](downloads/science-scope-embracing-uncertainty.pdf) - Science Scope article

## Tools

### Web Apps

*Can be integrated into CODAP*

- [Credibility Updater](https://ed-analytics.shinyapps.io/confidence-updater/) - Interactive tool for updating credibility assessments
- [CREDIBLE Local Data](https://ed-analytics.shinyapps.io/credible-local-data/) - Tool for working with local data in the CREDIBLE framework

### Web Apps (Can be integrated into CODAP)

- [Credibility Updater](https://ed-analytics.shinyapps.io/confidence-updater/) - Interactive tool for updating credibility assessments
- [CREDIBLE Local Data](https://ed-analytics.shinyapps.io/credible-local-data/) - Tool for working with local data in the CREDIBLE framework

## Get Involved

- [Apply to Project CREDIBLE](https://tiny.utk.edu/credible) - Join our next cohort
- **Questions?** Email us at [projectcredible@utk.edu](mailto:projectcredible@utk.edu)
